// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int i = 0;
		int less = 0;
		int more = 0;
		
		while (i < N){
			if (Math.random() > 0.5){
				more += 1;
			}
			else{
				less += 1;
			}
			i += 1;
		}

		Double ratio = (double) more / less;
		System.out.println("> 0.5: " + more);
		System.out.println("<= 0.5: " + less);
		System.out.println("Ratio: " + ratio);
	}
}
